### ISSUE TITLE
stats for 1 day vs. 2 days

### ISSUE THREAD

**Issue by mountrcg** [trixing/nightscout_tools#1]
A) When I view stats for 1 day it will show yesterdays values.
B) When I view 2 days it will show todays values and yesterday values, however yesterdays TDD in (B) is different than in (A)
C) repeat with days settings >2, TDD in (C) will be the same to (B) and different to (A)

**Comment by trixing** [comment]
Can you post screenshots / json? For me it looks like this

```
days=1 / tdd=27.4
    "daily": [
        {
            "date": "2022-02-20",
            "weekday": "Sun",
            "insulin": 27.4,

days=2
    "daily": [
        {
            "date": "2022-02-19",
            "weekday": "Sat",
            "insulin": 27.5,
        },
        {
            "date": "2022-02-20",
            "weekday": "Sun",
            "insulin": 27.4, == same as above
        }
    ],

```
similar with 3

Note that the most recent value is at the bottom.

**Comment by mountrcg** [comment]
So it seems to be that one one Saturday that yields different values, that is the same data error I was talking about above.

https://nshistory.trixing.net/rcgloop.herokuapp.com/stats.json?days=2

<img width="322" alt="Bildschirmfoto 2022-02-21 um 15 49 57" src="https://user-images.githubusercontent.com/539276/154978775-b6f5c21e-cb61-454e-a1be-3fdbef3fc03e.png">
<img width="279" alt="Bildschirmfoto 2022-02-21 um 15 50 19" src="https://user-images.githubusercontent.com/539276/154978779-dbe70495-e40f-4666-a1d3-2df042768de0.png">

**Comment by trixing** [comment]
Theory is that this might be happening due to a temp basal started on the previous day. But because the code right now is only getting the data for exactly the day it might miss that event. Hmm. Longest temp basals Loop/FAX set are 1 hour in practice, right?

**Comment by trixing** [comment]
Should be fixed now. There was indeed some issues across day boundaries.
