### ISSUE TITLE
Support authentication by token for secured NS sites 

### ISSUE THREAD

**Issue by bjornoleh** [trixing/nightscout_tools#2]
It would be good to enable use of secured NS sites with the web service for fetching TDD data. 

NS sites with `AUTH_DEFAULT_ROLES = denied` can be accessed by token authentication using an url like `https://yoursitename.herokuapp.com/?token=school-a595d5f0aeff64c0`

There is more info on the topic 

here:

http://nightscout.github.io/nightscout/security/#how-to-turn-off-unauthorized-access

And here:

https://github.com/nightscout/cgm-remote-monitor/wiki/API-v1-Security

**Comment by trixing** [comment]
This should work now. Both via token, or the api-secret in the header.

**Comment by bjornoleh** [comment]
Thanks, confirmed, working with token in the format `https://yoursitename.herokuapp.com/?token=school-a595d5f0aeff64c0`
